### ISSUE TITLE
Build Error When Installing "lua-geoip" by luarocks

### ISSUE THREAD

**Issue by yy1993** [agladysh/lua-geoip#23]
I cannot find where you declare constant GEOIP_SILENCE, neither does the compiler.
Please let me know how to install lua-geoip successfully.
Thanks!

see:
root@yy-luarocks-server:/# luarocks install lua-geoip
Installing http://luarocks.org/repositories/rocks/lua-geoip-0.2-1.src.rock
gcc -O2 -fPIC -I/usr/include/lua5.1 -c src/database.c -o src/database.o -Isrc/
gcc -O2 -fPIC -I/usr/include/lua5.1 -c src/country.c -o src/country.o -Isrc/
src/country.c: In function ‘lcountry_open’:
src/country.c:264:28: error: ‘GEOIP_SILENCE’ undeclared (first use in this function)
       GEOIP_MEMORY_CACHE | GEOIP_SILENCE,
                            ^
src/country.c:264:28: note: each undeclared identifier is reported only once for each function it appears in

Error: Build error: Failed compiling object src/country.o

**Comment by agladysh** [comment]
Please make sure that the geoip library is at least v1.6.3.

**Comment by yy1993** [comment]
Thank you so much! I install an old version of geoip library version mistakenly. Now it works.

**Comment by agladysh** [comment]
Happy to help!
